[versions]
compileSdk = "36"
targetSdk = "34"
appCompat = "1.7.1"
composeBom = "2024.10.01"
composeCompiler = "1.5.12"
activityCompose = "1.9.3"

[libraries]
appCompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appCompat" }
androidxActivityCompose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
composeBom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
composeMaterial3 = { group = "androidx.compose.material3", name = "material3" }
composeUiToolingPreview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
composeUiTooling = { group = "androidx.compose.ui", name = "ui-tooling" }
composeUiTestManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
